server:
  port: 9097
  tomcat:
    connection-timeout: 10000
    threads:
      max: 3000
      min-spare: 100
    keep-alive-timeout: 10000
    accesslog:
      enabled: true

spring:
  application:
    name: hello_world_rest


service:
  api:
    base-path: /services/${spring.application.name}

springdoc:
  swagger-ui:
    display-request-duration: true
    display-operation-id: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/${spring.application.name}/api-docs